### Place this file under directory fastlane/Fastfile
###  PR Android
###

desc "Pull Request verification"
lane :pull_request_verification do
gradle(project_dir: ".", task: "clean lintDebug test")

end