name: Android Pull Request

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pr-verification:
    name: PR Check Android
    runs-on: macos-latest
    steps:
      -   uses: actions/checkout@v2

      # Gems for Fastlane
      -   name: Cache ruby gems dependencies
          id: cache-gems
          uses: actions/cache@v2
          env:
            keyPath: ${{ runner.os }}-gems
          with:
            path: ~/.gem
            key: ${{ runner.os }}-build-${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
            restore-keys: ${{ runner.os }}-build-${{ env.keyPath }}-
      -   name: Install gem dependencies
          if: steps.cache-gems.outputs.cache-hit != 'true'
          run: bundle config set path '~/.gem' && bundle install
      -   name: Cache gradle dependences
          uses: actions/cache@v2
          env:
            gradle-cache-key: gradle-cache-android
            gradle-path: ~/.gradle
          with:
            path: ${{ env.gradle-path }}
            key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('android/buildSrc/**') }}
            restore-keys: ${{ runner.os }}-build-${{ env.gradle-cache-key }}
      -   name: Run pr check
          env:
            GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
            GITHUB_USER: ${{ secrets.REPO_USER }}
          run: bundle exec fastlane pull_request_verification
